#!/usr/bin/env python3
"""Validate the editable registers; generate an offline, aggregate-only dashboard.
No phone/network access. Passing this checker is not product acceptance.
"""
from pathlib import Path
from collections import Counter
import html
import json

ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parents[1]


def read(name):
    return json.loads((ROOT / name).read_text())


def validate(tasks_doc, score, baseline):
    tasks = tasks_doc['tasks']
    gates = score['gates']
    tids = [t['id'] for t in tasks]
    gids = [g['id'] for g in gates]
    assert len(tids) == len(set(tids)), 'Duplicate task ID'
    assert len(gids) == len(set(gids)), 'Duplicate gate ID'
    assert sum(g['weight'] for g in gates) == 100, 'Gate weights must total 100'
    for t in tasks:
        assert t['state'] in tasks_doc['states'], f"Invalid state: {t['id']}"
        assert t['priority'] in ('P0', 'P1', 'P2'), 'Invalid priority'
        assert set(t['gate_ids']) <= set(gids), f"Unknown gate: {t['id']}"
        assert set(t['depends_on']) <= set(tids), f"Unknown dependency: {t['id']}"
        assert t['id'] not in t['depends_on'], 'Self dependency'
        if t['state'] == 'COMPLETE':
            assert t['evidence'], f"Completed task has no evidence: {t['id']}"
        for path in t['evidence']:
            assert (ROOT / path).is_file(), f'Missing evidence: {path}'
        for path in t['implementation']:
            assert (ROOT / path).is_file() or (REPO / path).is_file(), f'Missing implementation: {path}'
    by_id = {t['id']: t for t in tasks}
    def visit(tid, ancestors):
        assert tid not in ancestors, f'Dependency cycle at {tid}'
        for dependency in by_id[tid]['depends_on']:
            visit(dependency, ancestors | {tid})
    for tid in tids:
        visit(tid, set())
    for g in gates:
        assert g['status'] in ('UNPROVEN', 'PARTIAL', 'FAIL', 'ACCEPTED'), 'Invalid gate status'
        for path in g['evidence']:
            assert (ROOT / path).is_file(), f'Missing gate evidence: {path}'
        if g['status'] == 'ACCEPTED':
            assert g['evidence'] and g['reviewer'] and g['reviewed_on'], f"Unreviewed acceptance: {g['id']}"
            assert g['evidence'] != ['evidence/baseline.json'], 'Historical mixed-build baseline cannot accept a gate alone'
    assert baseline['summary']['evaluation_complete'], 'Expected completed historical baseline'


def main():
    tasks_doc, score, baseline = read('tasks.json'), read('scorecard.json'), read('evidence/baseline.json')
    validate(tasks_doc, score, baseline)
    tasks, gates = tasks_doc['tasks'], score['gates']
    accepted = sum(g['weight'] for g in gates if g['status'] == 'ACCEPTED')
    critical = [g['id'] for g in gates if g['critical'] and g['status'] != 'ACCEPTED']
    decision = 'ACCEPTED FOR DEFINED PILOT SCOPE' if (
        accepted >= score['minimum_accepted_points'] and not critical and
        score['owner_ratified'] and score['seven_day_run_accepted'] and score['owner_defence_signed']
    ) else 'NOT DEFENSIBLE'
    def clean(value):
        return str(value).replace('|', '/').replace('\n', ' ')
    lines = ['# Progress checker', '', 'Generated from tasks.json and scorecard.json. Do not edit this file directly.', '',
        f"Register date: {tasks_doc['updated_on']}. **Decision: {decision}.**", '',
        f'Accepted evidence points: **{accepted}/100**. This is accepted evidence coverage, not a capability rating.',
        f"Critical gates not accepted: {', '.join(critical) or 'none'}.",
        f"Criteria ratified: {score['owner_ratified']}; seven-day run accepted: {score['seven_day_run_accepted']}; owner defence signed: {score['owner_defence_signed']}.", '',
        '## Gate review', '', '| Gate | Weight | Critical | Status | Reason |', '|---|---:|:---:|---|---|']
    lines += [f"| {g['id']} {g['title']} | {g['weight']} | {'Yes' if g['critical'] else 'No'} | {g['status']} | {clean(g['reason'])} |" for g in gates]
    lines += ['', '## Work status', '', '; '.join(f'{k}: {v}' for k, v in Counter(t['state'] for t in tasks).items()), '',
              'Task completion and product acceptance are separate. A deployed fix remains AWAITING_EVIDENCE until its live acceptance criterion is met.', '',
              '| Task | Priority | State | Dependencies | Next action |', '|---|---|---|---|---|']
    lines += [f"| {t['id']} — {t['title']} | {t['priority']} | {t['state']} | {', '.join(t['depends_on']) or 'None'} | {clean(t['next_action'])} |" for t in tasks]
    lines += ['', '## Review routine', '',
        '- Daily during a pilot: update coverage, customer dispositions, follow-ups, delivery outcomes, orders/costs and interventions.',
        '- After changes: link implementation and checks; retain AWAITING_EVIDENCE when live results are missing.',
        '- Weekly: review customer quality and business value; decide which experiment to retain, change or stop.',
        '- Before any 8/10 claim: ratify criteria, satisfy samples/critical gates, and complete the owner defence review.',
        '- Regenerate this page and the dashboard with `python3 mission/8-10-defence-goal/scripts/update_progress.py`.', '']
    (ROOT / 'PROGRESS.md').write_text('\n'.join(lines))
    payload = json.dumps(dict(tasks=tasks, score=score, baseline=baseline, accepted=accepted, decision=decision)).replace('<', '\\u003c')
    page = '''<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Amara · 8/10 defence</title>
<style>
:root{color-scheme:light;--ink:#162a32;--green:#087f70;--amber:#ad6811;--red:#b33640}*{box-sizing:border-box}body{font:16px/1.55 system-ui,sans-serif;color:var(--ink);background:#f1f5f4;margin:0}main{max-width:1150px;margin:auto;padding:28px}h1{font-size:clamp(28px,4vw,44px);margin:0}h2{font-size:23px}p{max-width:85ch}.tag{display:inline-block;padding:6px 12px;background:#ffe1db;border-radius:6px;font-weight:700}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:18px}section,.card{background:white;padding:22px;border-radius:12px;margin:18px 0;border:1px solid #dbe5e2}.grid .card{margin:0}.number{font-size:32px;font-weight:750}.note{color:#4e6167;font-size:14px}select{padding:9px;margin:4px;border:1px solid #a9bab7;background:white;border-radius:5px;font:inherit}.scroll{overflow-x:auto}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;padding:10px;border-bottom:1px solid #dbe5e2;vertical-align:top}th{background:#edf3f1}.track{height:26px;display:flex;background:#edf1f0;border-radius:4px;overflow:hidden;max-width:600px}.bar{height:100%;min-width:0}.verified{background:#087f70}.failed{background:#b33640}.uncertain{background:#ad6811}.legend span{display:inline-block;margin:0 16px 8px 0}.dot{display:inline-block;width:12px;height:12px;margin-right:6px}.chart-row{margin:16px 0}a{color:#075d6f}button{padding:8px 12px;cursor:pointer}summary{cursor:pointer;font-weight:650}.sub{font-size:13px;color:#4e6167}@media print{body{background:white}main{padding:0}section,.card{break-inside:avoid}button,select{display:none}}
</style>
<main><p>Mission / Sanaa Media / baseline 6 September 2026</p><h1>Amara: earn the owner's trust</h1><p id="decision" class="tag"></p>
<p>A complete customer-to-order journey, evidenced by useful replies, follow-through, relevant promotion and attributable value. This is a product acceptance dashboard, not a live phone monitor.</p>
<p><a href="../README.md">Mission index</a> · <a href="../DEFENCE.md">Acceptance rules</a> · <a href="../CURRENT-STATE.md">Current state</a> · <a href="../evidence/baseline.json">Source aggregate</a> · <button onclick="window.print()">Print / save PDF</button></p>
<div class="grid"><div class="card"><div class="number" id="points"></div><strong>Accepted evidence points</strong><p class="note">Zero accepted points means the gates are not yet proven. It does not mean Amara has zero capability.</p></div><div class="card"><div class="number">5 hours</div><strong>Historical mixed-build observation</strong><p class="note">08:56–13:56 UTC, 6 September. Engineering interventions occurred. The v5 recovery update was installed after this window.</p></div><div class="card"><div class="number">0 recorded</div><strong>Paid sales and revenue in baseline</strong><p class="note">Commercial policy was unconfigured. Unknown or untracked sales cannot be attributed to Amara.</p></div></div>
<section><h2>What the logs actually proved</h2><div class="legend"><span><i class="dot verified"></i>Verified</span><span><i class="dot failed"></i>Failed</span><span><i class="dot uncertain"></i>Uncertain</span></div><div id="effect-charts"></div><p class="note">Bar lengths show counts on a shared scale. Outcomes are final recorded transaction states, not views, customer satisfaction or conversions. Different activities have different denominators.</p><p id="inbound"></p><p class="note">Do not read 1/12 as a customer reply rate: accepted work includes superseded items. The available summary does not supply a complete unique-turn quality denominator.</p></section>
<section><h2>Evidence by build segment</h2><label for="segments">Historical segment</label> <select id="segments"></select><p class="note" id="segment-time"></p><div class="scroll"><table><thead><tr><th>Work kind</th><th>Outcome</th><th>Count</th></tr></thead><tbody id="segment-rows"></tbody></table></div><p class="note">Work outcomes can include retries and are not the same as unique external transaction receipts. v4 has group outcomes but no inbound outcomes; it does not prove the origin-routing fix delivered replies.</p></section>
<section><h2>The defence gates</h2><p>Proposed criteria require owner ratification, ≥80 accepted points, every critical gate, a qualifying seven-day run and owner sign-off.</p><div class="scroll"><table><thead><tr><th>Gate</th><th>Weight</th><th>Critical</th><th>Status</th><th>Evidence gap</th></tr></thead><tbody id="gates"></tbody></table></div></section>
<section><h2>Work toward the promise</h2><label for="module">Module</label><select id="module"><option value="">All</option></select><label for="state">State</label><select id="state"><option value="">All</option></select><p id="task-count" class="note"></p><div id="tasks"></div></section>
<footer><p class="note">Generated from editable mission registers. No external resources, private messages or credentials. Consult the evidence index for limitations. A successful build or passed test cannot certify product readiness.</p></footer></main>
<script id="data" type="application/json">PAYLOAD</script><script>
'use strict';
const d=JSON.parse(document.getElementById('data').textContent), el=id=>document.getElementById(id);
function text(tag,value,parent,cls){const n=document.createElement(tag);n.textContent=value;if(cls)n.className=cls;parent.append(n);return n;}
function tableRow(parent,values){const row=document.createElement('tr');values.forEach(v=>text('td',String(v),row));parent.append(row);}
el('decision').textContent=d.decision;el('points').textContent=d.accepted+' / 100';
const effects=d.baseline.summary.external_effects;
const groups=[['Group promotions','broadcast_group_whatsapp'],['TikTok posts','post_tiktok'],['TikTok comments','tiktok_public_comment']];
const max=Math.max(1,...groups.map(([,key])=>['VERIFIED','FAILED','UNCERTAIN'].reduce((n,s)=>n+(effects[key+':'+s]||0),0)));
for(const [label,key] of groups){const row=document.createElement('div');row.className='chart-row';text('strong',label,row);const track=document.createElement('div');track.className='track';let names=[];for(const state of ['VERIFIED','FAILED','UNCERTAIN']){const count=effects[key+':'+state]||0;names.push(count+' '+state.toLowerCase());const bar=document.createElement('div');bar.className='bar '+state.toLowerCase();bar.style.width=(100*count/max)+'%';bar.title=count+' '+state;track.append(bar);}row.append(track);text('div',names.join(' · '),row,'note');el('effect-charts').append(row);}
const s=d.baseline.summary;el('inbound').textContent='Inbound work: '+s.accepted_inbound+' accepted; '+s.verified_reply_outcomes+' verified reply; '+s.inbound_not_verified+' unresolved after supersession accounting. Only one reply latency sample.';
for(const g of d.score.gates)tableRow(el('gates'),[g.id+' '+g.title,g.weight,g.critical?'Yes':'No',g.status,g.reason]);
for(const [i,seg] of d.baseline.segments.entries()){const opt=text('option',seg.segment||'legacy-unlabelled',el('segments'));opt.value=i;}
function segments(){const seg=d.baseline.segments[Number(el('segments').value)];el('segment-rows').replaceChildren();el('segment-time').textContent=new Date(seg.first_event_ms).toISOString()+' — '+new Date(seg.last_event_ms).toISOString();for(const row of seg.outcomes)tableRow(el('segment-rows'),[row.kind,row.status,row.count]);}
el('segments').onchange=segments;segments();
for(const field of ['module','state'])for(const value of [...new Set(d.tasks.map(t=>t[field]))].sort()){const option=text('option',value,el(field));option.value=value;}
function tasks(){el('tasks').replaceChildren();const rows=d.tasks.filter(t=>(!el('module').value||t.module===el('module').value)&&(!el('state').value||t.state===el('state').value));el('task-count').textContent=rows.length+' of '+d.tasks.length+' tasks shown. Documentation completion is separate from product acceptance.';for(const t of rows){const det=document.createElement('details');text('summary',t.id+' · '+t.priority+' · '+t.title+' — '+t.state,det);text('p','Acceptance: '+t.acceptance,det);text('p','Next: '+t.next_action,det);text('p','Dependencies: '+(t.depends_on.join(', ')||'none')+' | Gates: '+(t.gate_ids.join(', ')||'none'),det,'sub');el('tasks').append(det);}}
el('module').onchange=tasks;el('state').onchange=tasks;tasks();
</script></html>'''.replace('PAYLOAD', payload)
    (ROOT / 'charts/dashboard.html').write_text(page)
    print(f'Validated {len(tasks)} tasks, {len(gates)} gates. {decision}. Accepted evidence points: {accepted}/100.')
    print('Generated PROGRESS.md and charts/dashboard.html. No device or production changes.')


if __name__ == '__main__':
    main()
