package co.sanaa.agent.core

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper
import org.json.JSONArray
import org.json.JSONObject

/**
 * ChatStore — stores full chat transcripts locally.
 * This is the key to making Amara remember conversations without heavy accessibility work.
 * Every message is stored as text. She can read her own memory.
 */
class ChatStore(context: Context) : SQLiteOpenHelper(context, "amara_chats.db", null, 1) {
    
    override fun onCreate(db: SQLiteDatabase) {
        db.execSQL("""
            CREATE TABLE IF NOT EXISTS chats (
                chat_key TEXT NOT NULL,
                sender TEXT NOT NULL,
                direction TEXT NOT NULL CHECK(direction IN ('sent','received')),
                message_text TEXT NOT NULL,
                timestamp INTEGER NOT NULL,
                platform TEXT DEFAULT 'whatsapp'
            )
        """)
        db.execSQL("CREATE INDEX IF NOT EXISTS idx_chats_key_time ON chats(chat_key, timestamp)")
        
        db.execSQL("""
            CREATE TABLE IF NOT EXISTS chat_summaries (
                chat_key TEXT PRIMARY KEY,
                summary TEXT NOT NULL,
                stage TEXT DEFAULT 'GREETING',
                last_activity INTEGER NOT NULL,
                message_count INTEGER DEFAULT 0
            )
        """)
        
        db.execSQL("""
            CREATE TABLE IF NOT EXISTS offerings (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                type TEXT NOT NULL CHECK(type IN ('PRODUCT','SERVICE')),
                name TEXT NOT NULL,
                price_ugx INTEGER,
                price_floor_ugx INTEGER,
                stock_count INTEGER,
                duration_minutes INTEGER,
                requires_booking INTEGER DEFAULT 0,
                description TEXT,
                source TEXT,
                synced_at INTEGER
            )
        """)
    }
    
    override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) {}
    
    /**
     * Store a message and update the chat summary atomically.
     * Uses a transaction to ensure chats and chat_summaries stay in sync.
     */
    fun storeMessage(chatKey: String, sender: String, direction: String, message: String, platform: String = "whatsapp") {
        val db = writableDatabase
        db.beginTransaction()
        try {
            db.execSQL(
                "INSERT INTO chats(chat_key, sender, direction, message_text, timestamp, platform) VALUES(?,?,?,?,?,?)",
                arrayOf(chatKey, sender, direction, message, System.currentTimeMillis().toString(), platform)
            )
            db.execSQL(
                "INSERT OR REPLACE INTO chat_summaries(chat_key, summary, stage, last_activity, message_count) " +
                "VALUES(?, COALESCE((SELECT summary FROM chat_summaries WHERE chat_key=?), ''), " +
                "COALESCE((SELECT stage FROM chat_summaries WHERE chat_key=?), 'GREETING'), ?, " +
                "COALESCE((SELECT message_count FROM chat_summaries WHERE chat_key=?), 0) + 1)",
                arrayOf(chatKey, chatKey, chatKey, System.currentTimeMillis().toString(), chatKey)
            )
            db.setTransactionSuccessful()
        } finally {
            db.endTransaction()
        }
    }
    
    fun getChatHistory(chatKey: String, limit: Int = 50): List<ChatMessage> {
        val cursor = readableDatabase.rawQuery(
            "SELECT sender, direction, message_text, timestamp FROM chats WHERE chat_key = ? ORDER BY timestamp DESC LIMIT ?",
            arrayOf(chatKey, limit.toString())
        )
        val messages = mutableListOf<ChatMessage>()
        while (cursor.moveToNext()) {
            messages.add(ChatMessage(cursor.getString(0), cursor.getString(1), cursor.getString(2), cursor.getLong(3)))
        }
        cursor.close()
        return messages.reversed()
    }
    
    fun getChatTranscript(chatKey: String, limit: Int = 30): String {
        val messages = getChatHistory(chatKey, limit)
        if (messages.isEmpty()) return "No previous conversation."
        return messages.joinToString("\n") { "${it.sender} (${it.direction}): ${it.text}" }
    }
    
    /**
     * Save a fresh summary generated by the LLM.
     * This is the correct way to update a chat's summary.
     */
    fun updateSummary(chatKey: String, summary: String, stage: String) {
        writableDatabase.execSQL(
            "INSERT OR REPLACE INTO chat_summaries(chat_key, summary, stage, last_activity, message_count) " +
                "VALUES(?,?,?, COALESCE((SELECT last_activity FROM chat_summaries WHERE chat_key=?), ?), " +
                "COALESCE((SELECT message_count FROM chat_summaries WHERE chat_key=?), 0))",
            arrayOf(chatKey, summary.take(8_000), stage, chatKey, System.currentTimeMillis().toString(), chatKey)
        )
    }

    /** Cloud-safe relationship memory: summaries and catalogue, never raw chat transcripts. */
    fun exportMemory(): JSONObject {
        val chats = JSONArray()
        readableDatabase.rawQuery(
            "SELECT chat_key, summary, stage, last_activity, message_count FROM chat_summaries WHERE summary <> '' ORDER BY last_activity DESC LIMIT 2000",
            null,
        ).use { cursor ->
            while (cursor.moveToNext()) chats.put(JSONObject()
                .put("chat_key", cursor.getString(0)).put("summary", cursor.getString(1))
                .put("stage", cursor.getString(2)).put("last_activity", cursor.getLong(3))
                .put("message_count", cursor.getInt(4)))
        }
        val offerings = JSONArray()
        readableDatabase.rawQuery(
            "SELECT type,name,price_ugx,price_floor_ugx,stock_count,duration_minutes,requires_booking,description,source,synced_at FROM offerings ORDER BY synced_at DESC LIMIT 1000",
            null,
        ).use { cursor ->
            while (cursor.moveToNext()) offerings.put(JSONObject()
                .put("type", cursor.getString(0)).put("name", cursor.getString(1))
                .put("price_ugx", if (cursor.isNull(2)) JSONObject.NULL else cursor.getLong(2))
                .put("price_floor_ugx", if (cursor.isNull(3)) JSONObject.NULL else cursor.getLong(3))
                .put("stock_count", if (cursor.isNull(4)) JSONObject.NULL else cursor.getInt(4))
                .put("duration_minutes", if (cursor.isNull(5)) JSONObject.NULL else cursor.getInt(5))
                .put("requires_booking", cursor.getInt(6) == 1).put("description", cursor.getString(7))
                .put("source", cursor.getString(8)).put("synced_at", cursor.getLong(9)))
        }
        return JSONObject().put("chat_summaries", chats).put("offerings", offerings)
    }

    /** Merge remote memory without replacing a newer local relationship summary. */
    fun importMemory(payload: JSONObject): Int {
        var merged = 0
        val db = writableDatabase
        db.beginTransaction()
        try {
            payload.optJSONArray("chat_summaries")?.let { chats ->
                for (i in 0 until chats.length()) {
                    val item = chats.optJSONObject(i) ?: continue
                    val key = item.optString("chat_key").trim()
                    val summary = item.optString("summary").trim()
                    if (key.isBlank() || summary.isBlank()) continue
                    db.execSQL(
                        "INSERT INTO chat_summaries(chat_key,summary,stage,last_activity,message_count) VALUES(?,?,?,?,?) " +
                            "ON CONFLICT(chat_key) DO UPDATE SET summary=excluded.summary,stage=excluded.stage,last_activity=excluded.last_activity,message_count=MAX(message_count,excluded.message_count) " +
                            "WHERE excluded.last_activity > chat_summaries.last_activity",
                        arrayOf(key, summary.take(8_000), item.optString("stage", "GREETING"), item.optLong("last_activity"), item.optInt("message_count")),
                    )
                    merged++
                }
            }
            payload.optJSONArray("offerings")?.let { rows ->
                for (i in 0 until rows.length()) {
                    val item = rows.optJSONObject(i) ?: continue
                    val type = item.optString("type")
                    val name = item.optString("name").trim()
                    if (type !in setOf("PRODUCT", "SERVICE") || name.isBlank()) continue
                    val remoteAt = item.optLong("synced_at")
                    val localAt = db.rawQuery(
                        "SELECT MAX(synced_at) FROM offerings WHERE type=? AND name=?", arrayOf(type, name),
                    ).use { if (it.moveToFirst() && !it.isNull(0)) it.getLong(0) else 0L }
                    if (remoteAt <= localAt) continue
                    db.delete("offerings", "type=? AND name=?", arrayOf(type, name))
                    db.execSQL(
                        "INSERT INTO offerings(type,name,price_ugx,price_floor_ugx,stock_count,duration_minutes,requires_booking,description,source,synced_at) VALUES(?,?,?,?,?,?,?,?,?,?)",
                        arrayOf<Any?>(
                            type, name, item.optNullableLong("price_ugx"), item.optNullableLong("price_floor_ugx"),
                            item.optNullableInt("stock_count"), item.optNullableInt("duration_minutes"),
                            if (item.optBoolean("requires_booking")) 1 else 0, item.optString("description"),
                            item.optString("source", "cloud_restore"), remoteAt,
                        ),
                    )
                    merged++
                }
            }
            db.setTransactionSuccessful()
        } finally { db.endTransaction() }
        return merged
    }

    private fun JSONObject.optNullableLong(key: String): Long? =
        if (!has(key) || isNull(key)) null else optLong(key)

    private fun JSONObject.optNullableInt(key: String): Int? =
        if (!has(key) || isNull(key)) null else optInt(key)
    
    /**
     * Save summary with stage — used by HumanConversationEngine.
     */
    fun saveSummary(chatKey: String, summary: String, stage: String) {
        updateSummary(chatKey, summary, stage)
    }
    
    fun getSummary(chatKey: String): String? {
        val cursor = readableDatabase.rawQuery("SELECT summary FROM chat_summaries WHERE chat_key = ?", arrayOf(chatKey))
        return try {
            if (cursor.moveToFirst()) cursor.getString(0) else null
        } finally {
            cursor.close()
        }
    }
    
    fun getStage(chatKey: String): String {
        val cursor = readableDatabase.rawQuery("SELECT stage FROM chat_summaries WHERE chat_key = ?", arrayOf(chatKey))
        return try {
            if (cursor.moveToFirst()) cursor.getString(0) else "GREETING"
        } finally {
            cursor.close()
        }
    }

    fun summaryCount(): Int = readableDatabase.rawQuery(
        "SELECT COUNT(*) FROM chat_summaries WHERE summary <> ''", null,
    ).use { if (it.moveToFirst()) it.getInt(0) else 0 }
    
    fun getDormantChats(daysSinceLastMessage: Int = 7): List<String> {
        val cutoff = System.currentTimeMillis() - (daysSinceLastMessage * 24 * 60 * 60 * 1000L)
        val cursor = readableDatabase.rawQuery(
            "SELECT chat_key FROM chat_summaries WHERE last_activity < ? AND stage NOT IN ('CONFIRMED','DORMANT')",
            arrayOf(cutoff.toString())
        )
        val chats = mutableListOf<String>()
        while (cursor.moveToNext()) chats.add(cursor.getString(0))
        cursor.close()
        return chats
    }
    
    // Offerings (unified products + services)
    fun storeOffering(type: String, name: String, price: Long?, priceFloor: Long?, stockCount: Int?, durationMins: Int?, requiresBooking: Boolean, description: String?, source: String) {
        require(type in setOf("PRODUCT", "SERVICE")) { "Unsupported offering type" }
        require(name.isNotBlank()) { "Offering name cannot be blank" }
        val db = writableDatabase
        db.beginTransaction()
        try {
            // A fresh Terminal observation replaces the prior cached row instead
            // of growing an unbounded list of duplicate offerings on every scan.
            db.delete("offerings", "type = ? AND name = ? COLLATE NOCASE", arrayOf(type, name.trim()))
            db.execSQL(
                "INSERT INTO offerings(type, name, price_ugx, price_floor_ugx, stock_count, duration_minutes, requires_booking, description, source, synced_at) VALUES(?,?,?,?,?,?,?,?,?,?)",
                arrayOf<Any?>(type, name.trim(), price, priceFloor, stockCount, durationMins, if (requiresBooking) 1 else 0, description, source, System.currentTimeMillis())
            )
            db.setTransactionSuccessful()
        } finally {
            db.endTransaction()
        }
    }
    
    fun getProducts(): List<String> {
        val cursor = readableDatabase.rawQuery("SELECT name, price_ugx FROM offerings WHERE type = 'PRODUCT' ORDER BY synced_at DESC LIMIT 20", null)
        val items = mutableListOf<String>()
        while (cursor.moveToNext()) {
            val name = cursor.getString(0)
            val price = if (cursor.isNull(1)) "price on request" else "UGX ${cursor.getLong(1)}"
            items.add("$name ($price)")
        }
        cursor.close()
        return items
    }
    
    fun getServices(): List<String> {
        val cursor = readableDatabase.rawQuery("SELECT name, price_ugx FROM offerings WHERE type = 'SERVICE' ORDER BY synced_at DESC LIMIT 20", null)
        val items = mutableListOf<String>()
        while (cursor.moveToNext()) {
            val name = cursor.getString(0)
            val price = if (cursor.isNull(1)) "price on request" else "UGX ${cursor.getLong(1)}"
            items.add("$name ($price)")
        }
        cursor.close()
        return items
    }
}

data class ChatMessage(val sender: String, val direction: String, val text: String, val timestamp: Long)
