package co.sanaa.agent.core.knowledge

import android.content.Context
import android.content.pm.PackageManager
import android.os.Build
import android.os.Environment
import android.os.StatFs
import java.io.File

/**
 * DeviceSelfKnowledge — Amara's model of her own environment.
 * She maintains a device map so she doesn't waste tokens exploring.
 * 
 * The map is stored as a skill file that she updates herself.
 * At startup, she reads it to know:
 * - Which apps are installed (and their packages)
 * - Where files are located
 * - What resources are available
 * - What she's learned about the device
 */
class DeviceSelfKnowledge(private val context: Context) {

    private val deviceMapFile = File(context.filesDir, "skills/device_map.md")
    private val knownApps = mutableMapOf<String, String>()  // name -> package

    data class DeviceInfo(
        val model: String,
        val manufacturer: String,
        val androidVersion: Int,
        val totalStorageMb: Long,
        val freeStorageMb: Long,
        val totalRamMb: Long,
        val screenWidth: Int,
        val screenHeight: Int,
        val density: Int,
        val imei: String?,  // null without permission
        val installedApps: Map<String, String>,
        val knownFilePaths: Map<String, String>
    )

    /**
     * Load or create the device map.
     */
    fun load(): String {
        if (!deviceMapFile.exists()) {
            buildDeviceMap()
        }
        return deviceMapFile.readText()
    }

    /**
     * Rebuild the device map from scratch.
     */
    fun rebuild(): String {
        return buildDeviceMap()
    }

    /**
     * Get a known app package by name.
     */
    fun getAppPackage(name: String): String? {
        refreshKnownApps()
        return knownApps[name.lowercase()]
    }

    /**
     * Check if an app is installed.
     */
    fun isInstalled(appName: String): Boolean {
        refreshKnownApps()
        return knownApps.containsKey(appName.lowercase())
    }

    /**
     * Get device info summary for prompts.
     */
    fun getSummary(): String {
        refreshKnownApps()
        val stat = StatFs(Environment.getDataDirectory().path)
        val freeMb = stat.availableBytes / (1024 * 1024)
        val totalMb = stat.totalBytes / (1024 * 1024)

        return buildString {
            appendLine("Device: ${Build.MANUFACTURER} ${Build.MODEL} (Android ${Build.VERSION.RELEASE})")
            appendLine("Storage: ${freeMb}MB free / ${totalMb}MB total")
            appendLine("Known apps: ${knownApps.keys.joinToString(", ")}")
        }
    }

    /**
     * Add a file path to the device map.
     */
    fun addFilePath(name: String, path: String) {
        val current = load()
        if (!current.contains("- $name: ")) {
            deviceMapFile.writeText("$current\n- $name: `$path`")
        }
    }

    /**
     * Add an app to the device map.
     */
    fun addApp(name: String, packageName: String) {
        knownApps[name.lowercase()] = packageName
        val current = load()
        if (!current.contains("- $name: `$packageName`")) {
            deviceMapFile.writeText("$current\n- $name: `$packageName`")
        }
    }

    private fun buildDeviceMap(): String {
        refreshKnownApps()

        val stat = StatFs(Environment.getDataDirectory().path)
        val freeMb = stat.availableBytes / (1024 * 1024)
        val totalMb = stat.totalBytes / (1024 * 1024)

        val content = buildString {
            appendLine("# Device Map")
            appendLine("Auto-generated by Amara. Updated: ${java.text.SimpleDateFormat("MMM dd, HH:mm").format(java.util.Date())}")
            appendLine()
            appendLine("## Hardware")
            appendLine("- Model: ${Build.MANUFACTURER} ${Build.MODEL}")
            appendLine("- Android: ${Build.VERSION.RELEASE} (API ${Build.VERSION.SDK_INT})")
            appendLine("- Storage: ${freeMb}MB free / ${totalMb}MB total")
            appendLine()
            appendLine("## Installed Apps")
            for ((name, pkg) in knownApps.toList().sortedBy { it.first }) {
                appendLine("- $name: `$pkg`")
            }
            appendLine()
            appendLine("## Known File Paths")
            appendLine("- App files: `${context.filesDir.absolutePath}`")
            appendLine("- Databases: `${context.filesDir.parent}/databases/`")
            appendLine("- Cache: `${context.cacheDir.absolutePath}`")
            appendLine()
            appendLine("## Capabilities")
            appendLine("- Accessibility: ${isAccessibilityEnabled()}")
            appendLine("- Internet: Check ConnectivityMonitor")
            appendLine()
            appendLine("## Notes")
            appendLine("- Amara adds to this as she learns the device")
        }

        deviceMapFile.parentFile?.mkdirs()
        deviceMapFile.writeText(content)
        return content
    }

    private fun refreshKnownApps() {
        if (knownApps.isNotEmpty()) return
        val pm = context.packageManager
        val apps = pm.getInstalledApplications(PackageManager.GET_META_DATA)
        for (app in apps) {
            val name = pm.getApplicationLabel(app).toString()
            knownApps[name.lowercase()] = app.packageName
        }
    }

    private fun isAccessibilityEnabled(): Boolean {
        val enabled = android.provider.Settings.Secure.getString(
            context.contentResolver,
            android.provider.Settings.Secure.ENABLED_ACCESSIBILITY_SERVICES
        ) ?: return false
        return enabled.contains(context.packageName)
    }

    /**
     * Get file path for the device map.
     */
    fun getFilePath(): String = deviceMapFile.absolutePath

    /**
     * Get all installed app names.
     */
    fun getInstalledAppNames(): Set<String> {
        refreshKnownApps()
        return knownApps.keys
    }
}
